# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Edit(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(387, 318)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 211, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 110, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 140, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 170, 55, 16))
        self.label_5.setObjectName("label_5")
        self.btn_editar = QtWidgets.QPushButton(Dialog)
        self.btn_editar.setGeometry(QtCore.QRect(160, 240, 93, 28))
        self.btn_editar.setStyleSheet("background-color: rgb(104, 255, 39);")
        self.btn_editar.setObjectName("btn_editar")
        self.btn_voltar = QtWidgets.QPushButton(Dialog)
        self.btn_voltar.setGeometry(QtCore.QRect(52, 240, 101, 28))
        self.btn_voltar.setStyleSheet("background-color: rgb(255, 114, 101);")
        self.btn_voltar.setObjectName("btn_voltar")
        self.input_id1 = QtWidgets.QLineEdit(Dialog)
        self.input_id1.setGeometry(QtCore.QRect(110, 110, 61, 22))
        self.input_id1.setMaxLength(9999)
        self.input_id1.setObjectName("input_id1")
        self.input_senha1 = QtWidgets.QLineEdit(Dialog)
        self.input_senha1.setGeometry(QtCore.QRect(110, 140, 61, 22))
        self.input_senha1.setText("")
        self.input_senha1.setMaxLength(99999999)
        self.input_senha1.setObjectName("input_senha1")
        self.input_status = QtWidgets.QLineEdit(Dialog)
        self.input_status.setGeometry(QtCore.QRect(110, 170, 61, 21))
        self.input_status.setObjectName("input_status")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(240, 60, 141, 121))
        self.label_6.setStyleSheet("image: url(:/add/cadastrar.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.btn_Search = QtWidgets.QPushButton(Dialog)
        self.btn_Search.setGeometry(QtCore.QRect(50, 40, 93, 28))
        self.btn_Search.setStyleSheet("background-color: rgb(75, 201, 255);")
        self.btn_Search.setObjectName("btn_Search")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(50, 10, 251, 22))
        self.lineEdit.setInputMask("")
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 391, 321))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_7.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.btn_editar.raise_()
        self.btn_voltar.raise_()
        self.input_id1.raise_()
        self.input_senha1.raise_()
        self.input_status.raise_()
        self.label_6.raise_()
        self.btn_Search.raise_()
        self.lineEdit.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "EDITAR USUARIO"))
        self.label_3.setText(_translate("Dialog", "ID"))
        self.label_4.setText(_translate("Dialog", "Senha"))
        self.label_5.setText(_translate("Dialog", "Status"))
        self.btn_editar.setText(_translate("Dialog", "Editar"))
        self.btn_voltar.setText(_translate("Dialog", "Voltar"))
        self.input_id1.setPlaceholderText(_translate("Dialog", "0"))
        self.input_senha1.setPlaceholderText(_translate("Dialog", "0"))
        self.input_status.setPlaceholderText(_translate("Dialog", " 1 - 2 - 3"))
        self.btn_Search.setText(_translate("Dialog", "Pesquisar"))
        self.lineEdit.setText(_translate("Dialog", "0"))
import templates.cadastro


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Edit()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
