# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginAcademy(object):
    def setupUi(self, LoginAcademy):
        LoginAcademy.setObjectName("LoginAcademy")
        LoginAcademy.resize(533, 477)
        self.label = QtWidgets.QLabel(LoginAcademy)
        self.label.setGeometry(QtCore.QRect(100, 60, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(LoginAcademy)
        self.label_3.setGeometry(QtCore.QRect(130, 290, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(LoginAcademy)
        self.label_4.setGeometry(QtCore.QRect(130, 330, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnLogin = QtWidgets.QPushButton(LoginAcademy)
        self.btnLogin.setGeometry(QtCore.QRect(110, 380, 321, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.btnLogin.setFont(font)
        self.btnLogin.setStyleSheet("background-color: rgb(45, 156, 39);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 8pt \"Arial Black\";\n"
"alternate-background-color: rgb(130, 207, 126);\n"
"")
        self.btnLogin.setObjectName("btnLogin")
        self.input_id1 = QtWidgets.QLineEdit(LoginAcademy)
        self.input_id1.setGeometry(QtCore.QRect(220, 290, 21, 22))
        self.input_id1.setObjectName("input_id1")
        self.input_senha1 = QtWidgets.QLineEdit(LoginAcademy)
        self.input_senha1.setGeometry(QtCore.QRect(220, 330, 21, 22))
        self.input_senha1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_senha1.setObjectName("input_senha1")
        self.btnConectar = QtWidgets.QPushButton(LoginAcademy)
        self.btnConectar.setGeometry(QtCore.QRect(10, 10, 93, 21))
        self.btnConectar.setStyleSheet("font: 75 8pt \"Arial\";\n"
"background-color: rgb(198, 229, 255);")
        self.btnConectar.setObjectName("btnConectar")
        self.line = QtWidgets.QFrame(LoginAcademy)
        self.line.setGeometry(QtCore.QRect(0, 30, 531, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.input_id2 = QtWidgets.QLineEdit(LoginAcademy)
        self.input_id2.setGeometry(QtCore.QRect(250, 290, 21, 22))
        self.input_id2.setObjectName("input_id2")
        self.input_senha2 = QtWidgets.QLineEdit(LoginAcademy)
        self.input_senha2.setGeometry(QtCore.QRect(250, 330, 21, 22))
        self.input_senha2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_senha2.setObjectName("input_senha2")
        self.input_senha3 = QtWidgets.QLineEdit(LoginAcademy)
        self.input_senha3.setGeometry(QtCore.QRect(280, 330, 21, 22))
        self.input_senha3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_senha3.setObjectName("input_senha3")
        self.input_senha4 = QtWidgets.QLineEdit(LoginAcademy)
        self.input_senha4.setGeometry(QtCore.QRect(310, 330, 21, 22))
        self.input_senha4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_senha4.setObjectName("input_senha4")
        self.label_2 = QtWidgets.QLabel(LoginAcademy)
        self.label_2.setGeometry(QtCore.QRect(100, 100, 331, 171))
        self.label_2.setStyleSheet("image: url(:/img/user-login.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.comboBox_COMS = QtWidgets.QComboBox(LoginAcademy)
        self.comboBox_COMS.setGeometry(QtCore.QRect(120, 10, 73, 22))
        self.comboBox_COMS.setObjectName("comboBox_COMS")
        self.label_5 = QtWidgets.QLabel(LoginAcademy)
        self.label_5.setGeometry(QtCore.QRect(-6, -5, 541, 481))
        self.label_5.setMinimumSize(QtCore.QSize(541, 481))
        self.label_5.setMaximumSize(QtCore.QSize(541, 481))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.btnEnviar = QtWidgets.QPushButton(LoginAcademy)
        self.btnEnviar.setGeometry(QtCore.QRect(250, 10, 121, 21))
        self.btnEnviar.setStyleSheet("background-color: rgb(42, 206, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.btnEnviar.setObjectName("btnEnviar")
        self.btnReceber = QtWidgets.QPushButton(LoginAcademy)
        self.btnReceber.setGeometry(QtCore.QRect(400, 10, 131, 21))
        self.btnReceber.setStyleSheet("background-color: rgb(42, 206, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.btnReceber.setObjectName("btnReceber")
        self.label_5.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.btnLogin.raise_()
        self.input_id1.raise_()
        self.input_senha1.raise_()
        self.btnConectar.raise_()
        self.line.raise_()
        self.input_id2.raise_()
        self.input_senha2.raise_()
        self.input_senha3.raise_()
        self.input_senha4.raise_()
        self.label_2.raise_()
        self.comboBox_COMS.raise_()
        self.btnEnviar.raise_()
        self.btnReceber.raise_()

        self.retranslateUi(LoginAcademy)
        QtCore.QMetaObject.connectSlotsByName(LoginAcademy)

    def retranslateUi(self, LoginAcademy):
        _translate = QtCore.QCoreApplication.translate
        LoginAcademy.setWindowTitle(_translate("LoginAcademy", "Dialog"))
        self.label.setText(_translate("LoginAcademy", "ELETRONIC LOCK SYSTEM - GYM IFMT"))
        self.label_3.setText(_translate("LoginAcademy", "ID"))
        self.label_4.setText(_translate("LoginAcademy", "Senha"))
        self.btnLogin.setText(_translate("LoginAcademy", "LOGIN"))
        self.input_id1.setPlaceholderText(_translate("LoginAcademy", "0"))
        self.input_senha1.setPlaceholderText(_translate("LoginAcademy", "0"))
        self.btnConectar.setText(_translate("LoginAcademy", "Conectar"))
        self.input_id2.setPlaceholderText(_translate("LoginAcademy", "0"))
        self.input_senha2.setPlaceholderText(_translate("LoginAcademy", "0"))
        self.input_senha3.setPlaceholderText(_translate("LoginAcademy", "0"))
        self.input_senha4.setPlaceholderText(_translate("LoginAcademy", "0"))
        self.btnEnviar.setText(_translate("LoginAcademy", "Enviar atualizações"))
        self.btnReceber.setText(_translate("LoginAcademy", "Receber atualizações"))
import templates.img


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginAcademy = QtWidgets.QDialog()
    ui = Ui_LoginAcademy()
    ui.setupUi(LoginAcademy)
    LoginAcademy.show()
    sys.exit(app.exec_())
